name: action1 basic

runs:
  using: "composite"
  steps: 
    - name: test-composite
      shell: bash           # ✅ REQUIRED to execute below commands
      run: | 
        echo "you will become Rich"