name: action5 basics

runs:
  using: "composite"
  steps:
    - name: use environment variable
      env:
        GOAL: "rich"
      shell: bash
      run: |
        echo "you will become ${{ env.GOAL }}"
        echo "----------"
        echo "you will become $GOAL"