name: 

inputs:
  goal:
    description: "Tell your goal"
    requried: true
    type: string

  package:
    description: "Tell your PKg"
    requried: true
    type: string 

outputs:
  ambition:
    value: ${{ steps.s1.outputs.var1}}   # ✅ only "value" key type need to be used here 
  
runs:
  using: "composite"
  steps:
    - name: step1
      id: s1
      run:
        echo "var1=${{ inputs.goal }}&${{inputs.package}}" >> $GITHUB_OUTPUT
      shell: bash