name: Deploy external Artifact

on:
  workflow_run:
    workflows: ["build-artifact"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from Build workflow
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show downloaded artifact
        run: cat build.txt