name: cache demo 1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          echo "you will be rich." >> test1.txt

      - name: Cache text file
        id: c1
        uses: actions/cache@v4
        with:
          path: test1.txt
          key: txt-cache-static

      - name: print output
        run: |
          echo "${{ steps.c1.outputs }}"
         
