name: Consumer Workflow 2

on: push

# <--- Here we will use same reusable workflow in different jobs in same file

jobs:
  j1:
    uses: ./.github/workflows/reusable2.yml
    with: 
      message: "You will become rich j1"
  j2:
    uses: ./.github/workflows/reusable2.yml
    with:
      message: "you will get 35 LPA"