name: Consumer Workflow 6
on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable4.yaml


  print-message:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - run: echo "Message:- ${{ needs.call-reusable.outputs.message }}"
