name: Consumer Workflow 3

on: push

# Here we will use different reusable workflow in different jobs in same file

jobs:
  j1:
    uses: ./.github/workflows/reusable3.1.yaml
    with:
      environemt: dev

  j2:
    uses: ./.github/workflows/reusable3.2.yaml
    with:
      stage: docker-build