name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Deployment environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable7.yaml
    with:
      deployEnv: ${{ inputs.env }}
