name: Matrix demo 2

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
        include:
          - os: ubuntu-latest
            node: 18
            special: true
          - os: macos-latest
            node: 16
            special: false
          - os: ubuntu-latest
            experiment: true
          - node: 18
            testing: true

          


    steps:
      - name: Print Info
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node: ${{ matrix.node }}"
          echo "Special: ${{ matrix.special }}"
          echo "experiment: ${{matrix.experiment}}"
          echo "testing: ${{matrix.testing}}"
