name: Matrix demo 2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 19]
        include:
          - node: 18
            environment: prod
    steps:
      - name: Echo environment
        run: echo "Node:- ${{ matrix.node }} | Environment:- ${{ matrix.environment || 'none' }}"
