## if all keys & values of matrix matches keys & values in include. Then Include job will not run it will override

name: Matrix Demo with Include Behavior

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16, 18]
        include:

          - os: ubuntu-latest
            node: 14

          - os: ubuntu-latest            
            node: 18
            special: true

          - os: ubuntu-latest
            node: 19
            special: false

          - os: ubuntu-latest             
            testing: true

          - os: macos-latest
            node: 16
            special: false

          - os: macos-latest
            experiment: true

          - node: 18                      
            become: rich

          - environments: dev

          - country: india

    steps:
      - name: Print Matrix Values
        run: |
          echo "OS:- ${{ matrix.os }}"
          echo "Node: ${{ matrix.node }}"
          echo "Special: ${{ matrix.special }}"
          echo "Experiment: ${{ matrix.experiment }}"
          echo "Testing: ${{ matrix.testing }}"
          echo "Environment: ${{ matrix.environments }}"
          echo "Country: ${{ matrix.country }}"
          echo "become: ${{ matrix.become }}"

