name: Quick Jobs Status Test

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 running"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print job1 status
        env:
          JOB1_STATUS: ${{ jobs.job1.status }}
        run: |
          echo "Job 1 status is $JOB1_STATUS"
          if [ "$JOB1_STATUS" = "success" ]; then
            echo "Job 1 succeeded!"
          else
            echo "Job 1 failed!"
          fi
