name: Quick Jobs Status Test

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 running"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 status: ${{ jobs.job1.status }}"
      - run: |
          if [ "${{ jobs.job1.status }}" = "success" ]; then
            echo "Job 1 succeeded!"
          else
            echo "Job 1 failed!"
          fi
