name: Quick Jobs Status Test

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 running"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Check job1 status
        if: ${{ needs.job1.result == 'success' }}
        run: echo "Job 1 succeeded!"
