name: Context Metadata 2 

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Who triggered this?
        run: echo 'Actor:- ${{ github.actor }}'

      - name: Which event?
        run: echo 'Event name:- ${{ github.event_name }}'

      - name: On which branch?
        run: echo 'Branch:- ${{ github.ref_name }}'

      - name: Commit info
        run: echo 'Commit SHA:- ${{ github.sha }}'

      - name: Show PR Title (only if PR)
        if: github.event_name == 'pull_request'
        run: echo 'PR Title:- ${{ github.event.pull_request.title }}'