## if all exact keys of matrix matches with keys of include. And if values of include is different then new job will create
## if no keys of matirx matches with keys of include no job will be created. But values are available to all jobs
## if all keys & values of matrix matches with all keys & values in include. Then job will be skip 
## if all keys & values of matrix matches all keys & values in include and it had extra key and value. Then extra key & value will be overide to base job
## if any one of the key from matrix matches any one of the key in include then it will not craete extra job but value is override to base job.

name: Matrix Demo with Include Behavior

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16, 18]
        include:

          - os: ubuntu-latest          x
            node: 14

          - os: ubuntu-latest          x 
            node: 18
            special: true

          - os: ubuntu-latest
            node: 19
            special: false

          - os: ubuntu-latest          x  
            testing: true

          - os: macos-latest
            node: 16
            special: false

          - os: macos-latest        
            experiment: true

          - node: 18                  x        
            become: rich

          - environments: dev         x

          - country: india            x

    steps:
      - name: Print Matrix Values
        run: |
          echo "OS:- ${{ matrix.os }}"
          echo "Node: ${{ matrix.node }}"
          echo "Special: ${{ matrix.special }}"
          echo "Experiment: ${{ matrix.experiment }}"
          echo "Testing: ${{ matrix.testing }}"
          echo "Environment: ${{ matrix.environments }}"
          echo "Country: ${{ matrix.country }}"
          echo "become: ${{ matrix.become }}"

