name: Contxt Jobs example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Testing..."

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check build job status
        env:
          BUILD_STATUS: ${{ jobs.build.status }}
        run: echo "Build job status:- $BUILD_STATUS"

      - name: Check test job status
        env:
          TEST_STATUS: ${{ jobs.test.status }}
        run: echo "Test job status:- $TEST_STATUS"

      - name: Conditional deploy
        if: ${{ jobs.build.status == 'success' && jobs.test.status == 'success' }}
        run: echo "Deploying because build and test succeeded!"
