# .github/workflows/problem1-with-include.yml
name: Matrix 1 demo

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16, 18]
        include:
          - os: windows-latest
            node: 20
    steps:
      - name: Show matrix values
        run: echo "OS:- ${{ matrix.os }}, Node:- ${{ matrix.node }}"
