name: Job Outputs Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - id: set_version
        run: echo "::set-output name=version::v1.0.0"
      - run: echo "Building version ${{ steps.set_version.outputs.version }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Testing version ${{ needs.build.outputs.version }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: |
          echo "Deploying version ${{ needs.build.outputs.version }}"
          echo "Build job outcome: ${{ jobs.build.outcome }}"
          echo "Test job outcome: ${{ jobs.test.outcome }}"
