name: Quick Jobs Status Test

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 running"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print success message if job1 succeeded
        if: ${{ jobs.job1.status == 'success' }}
        run: echo "Job 1 succeeded!"

      - name: Print failure message if job1 failed
        if: ${{ jobs.job1.status != 'success' }}
        run: echo "Job 1 failed!"
