name: Contxt Jobs example

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}
    steps:
      - name: Build step
        run: echo "Building..."

  test:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      test_status: ${{ job.status }}
    steps:
      - name: Test step
        run: echo "Testing..."

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check build job status
        run: echo "Build job status:- ${{ jobs.build.status }}"

      - name: Check test job status
        run: echo "Test job status:- ${{ jobs.test.status }}"

      - name: Conditional deploy
        if: ${{ jobs.build.status == 'success' && jobs.test.status == 'success' }}
        run: echo "Deploying because build and test succeeded!"
