name: Test container ENV 3

on: push

jobs:
  j1:
   runs-on: ubuntu-latest
   env:
     VAR1: ultra_rich
   container:
     image: centos:7
     env:
       VAR1: rich
   steps:
       # This step prints Step level env value only  (Ultra_super_rich)
     - name: print container env values
       env:
         VAR1: ultra_super_rich
       run: |
         echo "first env var: $VAR1"
         
  
