name: EndsWith function demo 1

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (e.g., prod-us, staging-eu)"
        required: true
        default: "prod-us"
      plan:
        description: "Plan (starter-plan, enterprise-pro)"
        required: true
        default: "starter-plan"

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, '-beta') }}
    steps:
      - name: Deploy Beta
        run: echo "Deploying beta version for tag:- ${{ github.ref }}"

  hotfix-api:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/hotfix/') && endsWith(github.ref, '-api') }}
    steps:
      - name: Build API hotfix
        run: echo "Running API-specific build for:- ${{ github.ref }}"

  regional-deploy:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.inputs.environment, '-us') }}
    steps:
      - name: Deploy to US Region
        run: echo "Deploying to US environment:- ${{ github.event.inputs.environment }}"

  plan-pro-check:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.event.inputs.plan, '-pro') }}
    steps:
      - name: Run extra checks for Pro plans
        run: echo "Running Pro Plan-only checks:- ${{ github.event.inputs.plan }}"

  matrix-os-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-lts, windows-latest, windows-lts]
    steps:
      - name: Run job only on LTS OS
        if: ${{ endsWith(matrix.os, '-lts') }}
        run: echo "This OS is LTS:- ${{ matrix.os }}"

  skip-docs-pr:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.ref, '-docs') }}
    steps:
      - name: Run if not a docs branch
        run: echo "This is not a documentation-only branch."

  file-extension-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set report file (simulated)
        id: generate
        run: echo "report_file=build/report-final.pdf" >> $GITHUB_OUTPUT

      - name: Upload only if report is PDF
        if: ${{ endsWith(steps.generate.outputs.report_file, '.pdf') }}
        run: echo "Uploading PDF report:- ${{ steps.generate.outputs.report_file }}"
