name: success demo1

on: push

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1: Run build
        run: npm run build

      - name: Step 2: Send Notification
        if: success()
        run: echo "✅ Build succeeded! Sending notification..."
