1. What is startsWith()?

startsWith() is an expression function that checks if a string begins with a specified substring.

2. Syntax

startsWith(string, searchString)

string — The full string you want to check.

searchString — The substring you want to check if it is at the start of string.

Returns: true or false

-----
Parameters Breakdown
-----

| Parameter      | Description                         | Example                                |
| -------------- | ----------------------------------- | -------------------------------------- |
| `string`       | The full string to check            | `github.ref` (`refs/heads/release/v1`) |
| `searchString` | The substring to check at the start | `'refs/heads/release/'`                |

3️⃣ Basic Examples

Example 1: Check if branch name starts with release/

if: ${{ startsWith(github.ref, 'refs/heads/release/') }}

github.ref could be: refs/heads/release/v1.0

This returns true because it starts with 'refs/heads/release/'.

Job/step runs only on release branches.

Example 2: Check if an input starts with prod

if: ${{ startsWith(inputs.environment, 'prod') }}

inputs.environment could be production or prod-staging.

Returns true if input starts with "prod".

5️⃣ Combining with Other Expressions

Example: Run if branch starts with feature/ AND contains -ui

if: ${{ startsWith(github.ref, 'refs/heads/feature/') && contains(github.ref, '-ui') }}

Only runs on branches like feature/login-ui, feature/header-ui.

Great for targeting specific feature branches.

6️⃣ Where to Use startsWith()?

| Use Case          | Explanation & Example                                                  |
| ----------------- | ---------------------------------------------------------------------- |
| Branch filtering  | Deploy only on branches starting with `release/` or `feature/`.        |
| Tag filtering     | Run on tags starting with `v` (version tags) like `v1.2.3`.            |
| Input validation  | Check if manual inputs start with specific prefixes.                   |
| Environment setup | Condition jobs based on environment variables starting with a pattern. |

# 1. Hotfix branch
if: ${{ startsWith(github.ref, 'refs/heads/hotfix/') }}

# 2. Environment input starts with "prod"
if: ${{ startsWith(inputs.environment, 'prod') }}

# 3. Branch starts with "feature/" and contains "api"
if: ${{ startsWith(github.ref, 'refs/heads/feature/') && contains(github.ref, 'api') }}

# 4. Tag starts with "v"
if: ${{ startsWith(github.ref, 'refs/tags/v') }}

