name: failure demo1

on: push

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1:- Run build
        run: |
          docker --version

      - name: Step 2:- Send Notification
        if: failure()
        run: echo "✅ Build succeeded! Sending notification..."
