name: success demo3

on: push

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1:- Run build
        run: |
          docker --version

      # Make this step fail, but mark it as continue-on-error
      - name: Step 1.1:- Fail this step
        id: step1_1
        continue-on-error: true
        run: |
          exit 1

      - name: Step 2:- based on outcome
        if: ${{ steps.step1_1.outcome == 'success' }}
        run: |
          echo "This step will not execute"
          echo "Outcome will capture actual result of steps even though we used continue_on_error"

      - name: Step2.1:- check success
        if: success()
        run: |
          echo "step 2.1 is success if step2 success"

      - name: Step 3:- based on conclusion
        if: ${{ steps.step1_1.conclusion == 'success' }}
        run: |
          echo "This step will execute"
          echo "Conclusion will not capture actual result it treat as success, because it uses continue_on_error"

      - name: Step3.1:- check success
        if: success()
        run: |
          echo "step 3.1 is success if step3 success"
