name: testing1

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        run: echo "1"
  j2:
    runs-on: ubuntu-latest
    steps:
      - name: testing2
        run: echo "2"

  j3:
    runs-on: ubuntu-latest
    steps:
      - name: testing3
        run: echo "3"