name: testing1

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        run: |
          node -v
          npm -v
          java -version
          python --version
          dotnet --version

  j2:
    runs-on: macos-latest
    steps:
      - name: testing2
        run: |
          sw_v

  j3:
    runs-on: windows-latest
    steps:
      - name: tesing3
        run: |
          systeminfo