name: testing1

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        run: echo "1"
  j2:
    runs-on: ubuntu-latest
    needs: j1
    steps:
      - name: testing2
        run: echo "2"