name: branch-filter2

on:
  push:
    branches-ignore:
      - test1
      - test2

jobs:
   branchignore:
     runs-on: ubuntu-latest
     steps:
       - name: test1
         run: echo "only execute other than test1 or test2 branch"
      