name: branch-filter2-based-on-push

on:
  push:
    branches-ignore:
      - test1
      - test2
      - main

jobs:
   branchignore:
     runs-on: ubuntu-latest
     steps:
       - name: test1
         run: echo "only execute other than test1/test2/main branch"
      