name: path-filter2-based-on-push

on:
  push:
    # make sure that branch and path order is important or else filter will be ignored
    branches:
      - main
      - test1
    paths:
      - "**/*.txt" # Any .txt file in any directory

jobs:
  path-and-branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "run any change in .txt file in main or test1 branch" 