name: branch-filter-on-workflow-run

on:
  workflow_run:
    workflows:
      - event1
    branches:
      - main
      - test1
    types:
      - completed

jobs:
  branch-filter-on-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "trigger if event1 wf completed from main/test1 branch"