name: ghw-workflow-dispatch2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select env"
        type: choice
        default: dev
        option:
          - dev
          - test
          - prod

jobs:
  options:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "ok."