name: ghw-workflow-dispatch2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select which env you nwant to deploy"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - test
          - prod

jobs:
  options:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          echo "ok."
          echo ${{github.event.inputs.environment}}