name: ghw-workflow-dispatch2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select which env you nwant to deploy"
        type: choice
        requried: true
        default: dev
        options:
          - dev
          - test
          - prod

jobs:
  options:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "ok."