name: ghw-workflow-dispatch3

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        type: boolean
        required: true
        default: false

jobs:
  boolean:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          echo ${{github.event.inputs.debug}}
          echo "In dashboard you will get checkbox to enable or not for debug"
          echo "if you click on checkbox it will be true or else it will be false"
