name: testing2

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "::error::Missing semicolon"
      
      - name: step2
        run: |
          secret="youwillbecomerich"
          echo "::add-mask::$secret"
          echo "$secret"

      - name: step3
        run: |
          echo "$secret"
    