name: ghw-workflow-dispatch5

on:
  workflow_dispatch:
    inputs:
      cloud_region:
        description: "select your cloud region to run"
        type: choice
        required: true
        default: dev
        options:
          - usa
          - ind
          - uk
          - jp
      debug:
        description: "do you want to enable debug mode"
        type: boolean
        required: true
        defualt: false
      tag:
        description: "purpose of run"
        type: string
        required: true
        default: "Testing"
      count:
        description: "Number of replicas"
        type: number 
        requried: true
        default: 4
      environment:
        description: "select your environment"
        type: environment
        required: true

jobs:
  select_options:
    runs-on: ubuntu-latest
    steps:
      - name: options
        run: |
          echo "Environment: ${{github.event.inputs.cloud_region}}"
          echo "Debug Enabled: ${{github.event.inputs.debug}}"
          echo "tag: ${{github.event.inputs.tag}}"
          echo "replicas: ${{github.event.inputs.count}}"
          echo "Env: ${{github.event.inputs.environment}}"