name: logical-function

on: push
jobs:
  logic_fun:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "step1 is success"

      - name: step2
        if: success()
        run: |
          echo "step2 is failed"
          exit 1

      - name: step3
        if: failure()
        run: |
          echo "step3 will run because step2 failed and we used fail()"

      - name: step3.1
        if: ${{steps.step3.outcome == 'success'}}
        run: |
          echo "step3.1 will run successfully"

      - name: step4
        if: success()
        run: |
         echo "step4 will not run because previous step (step3) was only conditional on failure"

      - name: step5
        if: success() || failure()
        run: |
          echo "step5 will run no matter what is previous steps"