name: logical-function-at-job-level

on: push
jobs:
  logic_fun1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "step1 is success"

      - name: step2
        if: success()
        run: |
          echo "step2 will execute and we will make step2 failed"
          exit 1

      - name: step3
        id: step3  # here we need to use id which is used by step3.1
        if: failure()
        run: |
          echo "step3 will run because step2 failed and we used failed() function here"

      - name: step3.1
        if: ${{steps.step3.outcome == 'success'}}
        run: |
          echo "step3.1 will not run because step3 bydefault it marked as fail"

      - name: step4
        if: success()
        run: |
          echo "step4 will not run because previous step (step3.1 is depends on step3)"
          echo "step3 is fail because we used failure() but step3 will execute and print."

      - name: step5
        if: success() || failure()
        run: |
          echo "step5 will run no matter what is previous steps"

      - name: step6
        if: ${{ steps.step3.outcome == 'success' && always() }}
        run: |
          echo "step6 will run because we used always() with step3"

  logical_func2:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: lf2_step1
        run: |
          echo "This job and step will run eventhough job1 is failed because"
          echo "This job is not depends on job1"

  logical_func3:
    needs: logic_fun1
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: lf3_step1
        run: |
          echo "This job and step will not run because"
          echo "This job is depends on job1"
      