name: Python CI

on:
  push:
    branches:
      - main

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: /home/runner/work/ghlearning/ghlearning/src/apps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with coverage
        working-directory: src/apps
        run: |
          pytest --cov=app --cov-report=term-missing

      - name: Check Docker version
        run: |
          docker --version

      - name: Build Docker Image
        working-directory: /home/runner/work/ghlearning/ghlearning/src/
        run: |
          docker image build -t app:v1 .

      - name: Check Docker image
        run: |
          docker image ls -a

      - name: loginto Nexus Repo
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login https://0a1f70a3c196-10-244-5-187-5000.papa.r.killercoda.com -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

      - name: Tag and Push to Nexus
        run: |
          docker tag app:v1 0a1f70a3c196-10-244-5-187-5000.papa.r.killercoda.com/docpy/app:v1 
          docker push 0a1f70a3c196-10-244-5-187-5000.papa.r.killercoda.com/docpy/app:v1
 
          