name: testing 4

on: push

defaults:
  run:
    working-directory: /home/runner

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        run: |
          ls -a
          pwd

      - name: testing2
        run: pwd