name: testing 4

on: push

defaults:
  run:
    working-directory: /home/runner

jobs:
  j0:
    runs-on: ubuntu-latest
    steps:
      - name: testing0
        run: |
          pwd
  j1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home
    steps:
      - name: testing1
        run: |
          ls -a
          pwd

      - name: testing2
        working-directory: /home/runner
        run: pwd