name: branch-filter

on:
  push:
    branches:
      - feature/*
      - bug/*
      - main


jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        echo: "Testing branch filters"