name: branch-filter1

on:
  push:
    branches:
      - feature/*
      - bug/*
      - main


jobs:
  branch-filter:
    runs-on: ubuntu-latest
    steps:
      - name: testing1
        run: echo "Testing branch filters"