name: Test Composite action 1

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo  # ✅ REQUIRED to access local action
        uses: actions/checkout@v4
        
      - name: test1
        uses: ./.github/actions/test-action1