name: test composite action 5

on: push

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: step1
        uses: ./.github/actions/test-action3
        with:
          goal: "rich"

      - name: step2
        uses: ./.github/actions/test-action3
        with:
          goal: "rich"
          package: "50lpa"