name: test composite action 5

on: push

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:

      - name: check shell is requried ?
        run: |
          echo "here it prints without define default shell as bash"
          echo "but if we not define shell in composite action then it fails"

      - name: checkout
        uses: actions/checkout@v4

      - name: step1
        uses: ./.github/actions/test-action3
        with:
          goal: "rich"

      - name: step2
        uses: ./.github/actions/test-action3
        with:
          goal: "rich"
          package: "50lpa"