name: test composite action 7

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: composite actions
        uses: ./.github/actions/test-action5