name: Basic GITHUB_TOKEN 2

on: [push]

jobs:
  create-issue1:
    # This Job will fail because of no permission provided to create new Issue using Github Tocken
    runs-on: ubuntu-latest

    steps:
      - name: Make an API call using GITHUB_TOKEN to create new issue
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"title":"Automated Issue","body":"This issue was created by GitHub Actions using GITHUB_TOKEN."}'
  
    create-issue2:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # ⬅️ Required 

    steps:
      - name: Create a new issue using GITHUB_TOKEN
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"title":"Test issue from Actions","body":"This issue was created by GitHub Actions."}'