name: Basic GITHUB_TOKEN 2

on: [push]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Make an API call using GITHUB_TOKEN
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{"title":"Automated Issue","body":"This issue was created by GitHub Actions using GITHUB_TOKEN."}'
