name: Publish Python Package

on: [ push ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine

      - name: Build the package
        working-directory: simple_package/
        run: |
          python setup.py sdist bdist_wheel
          ls
          cd dist
          ls

      - name: Publish to GitHub Packages
        working-directory: simple_package/
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload \
            --repository-url https://api.github.com/orgs/${{ github.repository_owner }}/packages/pypi/upload \
            --verbose \
            dist/*

