name: reusable 8 Parent

on:
  workflow_call:
    inputs:
      deployEnv:
        type: string
        required: true
      skipTests:
        type: boolean
        required: false
        default: false

jobs:
  build-test:
    uses: ./.github/workflows/reusable8.2.yaml
    with:
      buildEnv: ${{ inputs.deployEnv }}

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-test.outputs.build_status == 'success' }}
    env:
      DEPLOY_ENV: ${{ inputs.deployEnv }}

    steps:
      - run: echo "Deploying to $DEPLOY_ENV environment!"
