name: Reusable 2

on:
  workflow_call: # <--- Enables it to be called from other workflows
    inputs:
      message:
        required: true
        type: string
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"
