name: Test secret 1

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    # assign secrets to environment variables using env:
    env:
      N_USERID: ${{secrets.NEXUS_USERNAME}}
      N_PASSWD: ${{secrets.NEXUS_PASSWORD}}
    steps:
      - name: print seceret defined in repo level
        run: |
          echo "Nexus Artifact user name: $N_USERID"
          echo "Nexus Artifact Password: $N_PASSWD"