name: Test secret 4

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    env:
      VAR1: rich
    steps:

      - name: Create deploy script
        run: |
          echo "#!/bin/bash" > deploy.sh
          echo "echo ' Secret Token is: $DEPLOY_TOKEN'" >> deploy.sh
          echo "echo ' Env var is: $VAR1'" >> deploy.sh

      - name: Run script with exported secret and env
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.NEXUS_USERNAME }}
