name: Test secret 3

on: push

jobs:
  j1:
    runs-on: ubuntu-latest
    # Using Secrets and env vars in Scripts with Export
    env:
      VAR1: rich
    steps:
      - name: Insert secret and env var in bash scripts
        run: |
          echo "#!/bin/bash" > script.sh
          echo "echo ' Secret Token is: $TOKEN'" >> script.sh
          echo "echo ' Env var is: $VAR1'" >> script.sh

      - name: Export secret and env vars in runner machine
        run: |
          export TOKEN=${{ secrets.NEXUS_USERNAME }}
          export VAR1=${{env.VAR1}}

      - name: execute scritp
        run: |
          chmod +x script.sh
          cat script.sh
          ./script.sh

# *** It will print ***
# Secret Token is: 
# Env var is: rich