name: test self hosted runners 2

on: push

jobs:
  j1:
    runs-on: [self-hosted, komp]  # use labels only, not runner name
    steps:
      - name: testing-r03
        run: |
          echo "this is for .. ${{runner.name}}."
    

  j2:
    runs-on: [self-hosted, 1c]  # use labels only, not runner name
    steps:
      - name: testing-r04
        run: |
          echo "this is ..... ${{runner.name}}"
      
  
  j3:
    runs-on: [self-hosted, 50lpa]  # use labels only, not runner name
    steps:
      - name: testing-rs03
        run: echo "this is ....... ${{runner.name}}"


  j4:
    runs-on: [self-hosted, 75lpa]  # use labels only, not runner name
    steps:
      - name: testing-rs04
        run: |
          echo "this is for .. ${{runner.name}}"

  