name: test self hosted runners 2

on: push

jobs:
  j1:
    runs-on: [self-hosted, ro3]
    steps:
      - name: testing-r03
        run: |
          echo "this is for .. ${{runner.name}}."
          sleep 50

  j2:
    runs-on: [self-hosted, r04]
    steps:
      - name: testing-r04
        run: |
          echo "this is ..... ${{runner.name}}"
          sleep 15
  
  j3:
    runs-on: [self-hosted, rs03]
    steps:
      - name: testing-rs03
        run: echo "this is ...... ${{runner.name}}"


  j4:
    runs-on: [self-hosted, rso4]
    steps:
      - name: testing-rs04
        run: |
          echo "this is for .. ${{runner.name}}"

  