name: setup1

on: push

jobs:
  test:
    runs-on: [self-hosted, dk-run1]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
           cd src/apps
           pip install -r requirements.txt 

      - name: check pkg
        run: |
          git --version
          docker --version
          echo "${{ runner.name }}"
