name: test runner 2

on: workflow_dispatch

jobs:
  j1:
    runs-on: [self-hosted, linux]
    steps:
      - name: docker testing
        run: |
          echo "this is for testing........."
          echo "this is for testing........."
          echo "${{ runner.os}}"
          touch file1.txt
          echo "you will be rich" >> file1.txt
          touch file2.txt
          touch file3.txt
          touch file4.txt