name: test runner 1

on: workflow_dispatch

jobs:
  j1:
    runs-on: [self-hosted, linux]
    steps:
      - name: docker testing
        run: |
          echo "this is for testing........."
          echo "this is for testing........"
          echo "${{ runner.os}}"
          touch file1.txt
          touch file2.txt
          touch file3.txt
          touch file4.txt
  j2:
    runs-on: [self-hosted, linux]
    needs: j1
    steps:
      - name: print
        run: |
          ls