name: test runner 1

on: push

jobs:
  j1:
    runs-on: [self-hosted, rich1]
    steps:
      - name: testing-r1
        run: |
          echo "this is for .. ${{runner.name}}."
          sleep 50

  j2:
    runs-on: [self-hosted, rich2]
    steps:
      - name: testing-r2 
        run: |
          echo "this is ..... ${{runner.name}}"
          sleep 15
  
  j3:
    runs-on: [self-hosted, 35lpa]
    steps:
      - name: testing-r2
        run: echo "this is ...... ${{runner.name}}"


  j4:
    runs-on: [self-hosted, rich1]
    steps:
      - name: testing-r1
        run: |
          echo "this is for .. ${{runner.name}}"

  j5:
    runs-on: [self-hosted, 40lpa]
    steps:
      - name: testing-r2
        run: echo "this is ...... ${{runner.name}}"


  j6:
    runs-on: [self-hosted, 45lpa]
    steps:
      - name: testing-r1
        run: |
          echo "this is for .. ${{runner.name}}"
          sleep 20

  j7:
    runs-on: [self-hosted, 40lpa, hyd]
    needs: j5
    steps:
      - name: testing-r2
        run: echo "this is ...... ${{runner.name}}"


  j8:
    runs-on: [self-hosted, 45lpa, hyd]
    needs: j6
    steps:
      - name: testing-r1
        run: |
          echo "this is for .. ${{runner.name}}"
