name: test runner 1

on: push

jobs:
  j1:
    runs-on: [self-hosted, docker]
    steps:
      - name: testing
        run: |
          echo "this is for testing........."
          echo "this is for testing........."