name: Test Context Expansion

on: [push]

jobs:
  test-expansion:
    runs-on: ubuntu-latest

    env:
      BRANCH_WITH: ${{ github.ref_name }}
      BRANCH_WITHOUT: github.ref_name

    steps:
      - name: Print env variables in single-line run
        run: |
          echo "BRANCH_WITH: $BRANCH_WITH"
          echo "BRANCH_WITHOUT: $BRANCH_WITHOUT"

      - name: Use context in run command with ${{ }} (will expand)
        run: echo 'Direct context with ${{}}:-' ${{ github.ref_name }}

      - name: Use context in run command without ${{ }} (literal)
        run: echo "Direct context without \${{ }}:- github.ref_name"

      - name: Use context in if condition (with ${{ }}) — will run only on main branch
        if: ${{ github.ref_name == 'main' }}
        run: echo "This runs only on the 'main' branch"
