name: Test Output

on: push

jobs:
  test-output:
    runs-on: ubuntu-latest

    outputs:
      my-message: ${{ steps.set-message.outputs.message }}

    steps:
      - name: Set Output
        id: set-message
        run: echo "message=Hello World" >> $GITHUB_OUTPUT

      - name: Print Output from Step
        run: echo "Step Output:- ${{ steps.set-message.outputs.message }}"
