What Are Context Variables in GitHub Actions?

Context variables are read-only, structured data provided by GitHub at runtime to help you understand and control your workflow's behavior. These are accessed via ${{ <context>.<property> }} syntax.

They are evaluated by GitHub before runner execution, and are used in:

if: conditions

env:, run:, with:, name: fields

Expressions in matrix, strategy, outputs, and more

✅ Context Variable Syntax

${{ context.property }}
Example:

${{ github.actor }}
${{ github.event.pull_request.title }}
${{ runner.os }}
${{ matrix.node }}

📚 Categories of Context Variables

Let’s explore each context type with examples and usage details.

1️⃣ github — GitHub & Event Context

Description:

Contains metadata about the repository, event type, actor, branch, commit, etc.

| Property            | Description                | Example                   |
| ------------------- | -------------------------- | ------------------------- |
| `github.repository` | "owner/repo"               | `"octocat/hello-world"`   |
| `github.actor`      | Who triggered the workflow | `"octocat"`               |
| `github.event_name` | Triggering event           | `"push"`                  |
| `github.ref_name`   | Branch or tag name         | `"main"`                  |
| `github.sha`        | Commit SHA                 | `"9fceb02"`               |
| `github.event`      | Full event payload (JSON)  | `{ pull_request: {...} }` |

Example:

steps:
  - run: echo "Triggered by: ${{ github.actor }} on branch ${{ github.ref_name }}"

PR-specific example:

if: github.event.pull_request.merged == true


2️⃣ runner — Runner System Info

| Property      | Description    | Example            |
| ------------- | -------------- | ------------------ |
| `runner.os`   | OS name        | `Linux`, `Windows` |
| `runner.arch` | Architecture   | `X64`              |
| `runner.name` | Name of runner | `Hosted Agent`     |

Example:

steps:
  - run: echo "Running on ${{ runner.os }}"

3️⃣ env — Environment Variables

${{ env.MY_VAR }}


4️⃣ vars — Repository or Organization Variables

Description:

Static configuration values set in the GitHub UI under repo/org settings → Variables.

${{ vars.DEPLOY_REGION }}

5️⃣ secrets — Secure Secrets

Description:

Securely stored secrets from repository/org settings.

${{ secrets.API_KEY }}

They are masked in logs and not available during expression evaluation outside GitHub (e.g., if: using secrets won’t work unless in run: block or secure use).

6️⃣ matrix — Matrix Strategy Variables

Used inside matrix jobs:

strategy:
  matrix:
    node: [14, 16]
run: echo "Using Node version ${{ matrix.node }}"

7️⃣ steps — Outputs of Steps

Access outputs or results from a previous step:

${{ steps.build.outputs.artifact_path }}

8️⃣ job & jobs — Job Status and Outputs

${{ job.status }}
${{ jobs.test.outputs.version }}

9️⃣ needs — Dependency Job Outputs

needs: build
run: echo "Version: ${{ needs.build.outputs.version }}"

1️⃣0️⃣ strategy — Strategy-level info

${{ strategy.job-index }}
${{ strategy.fail-fast }}

1️⃣1️⃣ inputs — Inputs from workflow_dispatch or reusable workflows

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'

run: echo "Env: ${{ inputs.environment }}"

🔍 Example: Using Multiple Contexts Together

env:
  DEPLOY_REGION: ${{ vars.REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - run: |
          echo "Deploying to region: ${{ env.DEPLOY_REGION }}"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Matrix OS: ${{ matrix.os }}"


----------------

| Type        | Mutable | Example Usage                       | Supports Dynamic Assignment? |
| ----------- | ------- | ----------------------------------- | ---------------------------- |
| `github.*`  | ❌ No    | `${{ github.actor }}`               | ❌                            |
| `runner.*`  | ❌ No    | `${{ runner.os }}`                  | ❌                            |
| `env.*`     | ✅ Yes   | `${{ env.MY_VAR }}`                 | ✅                            |
| `secrets.*` | ❌ No    | `${{ secrets.MY_SECRET }}`          | ❌                            |
| `steps.*`   | ✅ Yes   | `${{ steps.step1.outputs.foo }}`    | ✅                            |
| `needs.*`   | ✅ Yes   | `${{ needs.job1.outputs.version }}` | ✅                            |
| `inputs.*`  | ❌ No    | `${{ inputs.environment }}`         | ❌                            |



------------------

Top Most Commonly Used GitHub Actions Contexts

------------------


1️⃣ github (🏆 Most Used)

| Property                  | Description                    | Example                    |
| ------------------------- | ------------------------------ | -------------------------- |
| `github.repository`       | Full name of repo              | `"octocat/hello-world"`    |
| `github.repository_owner` | Owner of repo                  | `"octocat"`                |
| `github.ref`              | Full ref path                  | `"refs/heads/main"`        |
| `github.ref_name`         | Branch or tag name             | `"main"`                   |
| `github.sha`              | Commit SHA triggering workflow | `"a1b2c3d4..."`            |
| `github.actor`            | Username of triggerer          | `"johnsmith"`              |
| `github.event_name`       | Event type                     | `"push"`, `"pull_request"` |
| `github.workflow`         | Name of the workflow           | `"CI Pipeline"`            |
| `github.run_id`           | Unique run ID                  | `"321123"`                 |
| `github.run_number`       | Incremental number of run      | `"25"`                     |
| `github.event`            | Full event payload             | Complex JSON               |
| `github.head_ref`         | Head branch (for PRs)          | `"feature-xyz"`            |
| `github.base_ref`         | Base branch (for PRs)          | `"main"`                   |
   
    Complete Reference: github Context Properties

| Property           | Description                                                        |
| ------------------ | ------------------------------------------------------------------ |
| `action`           | Name of the action currently running                               |
| `actor`            | Username of the person or app that initiated the workflow          |
| `base_ref`         | The base ref or branch of the pull request                         |
| `event_name`       | The name of the event that triggered the workflow                  |
| `event`            | The full webhook event payload                                     |
| `head_ref`         | The branch of the pull request from where changes are coming       |
| `job`              | The ID of the current job                                          |
| `ref`              | The full ref that triggered the workflow (e.g., `refs/heads/main`) |
| `ref_name`         | Short ref name (e.g., `main`, `v1.0`)                              |
| `ref_type`         | Type of ref (branch or tag)                                        |
| `repository`       | Full repo name (e.g., `octocat/my-repo`)                           |
| `repository_owner` | Owner of the repository                                            |
| `run_id`           | Unique ID of the workflow run                                      |
| `run_number`       | Sequential run number                                              |
| `server_url`       | URL of GitHub server                                               |
| `sha`              | Commit SHA that triggered the workflow                             |
| `workflow`         | Name of the workflow                                               |
| `triggering_actor` | The user who initiated the workflow (can differ from `actor`)      |
| `workspace`        | Path to the GitHub workspace directory                             |


2️⃣ env

| Property         | Usage                                   |
| ---------------- | --------------------------------------- |
| `env.MY_ENV_VAR` | Read/write custom environment variables |
| `$MY_ENV_VAR`    | Used in shell script                    |


3️⃣ secrets

| Property                    | Example            |
| --------------------------- | ------------------ |
| `secrets.AZURE_CREDENTIALS` | Azure login        |
| `secrets.DOCKER_PASSWORD`   | Docker Hub push    |
| `secrets.SLACK_WEBHOOK`     | Notification hooks |


4️⃣ runner

| Property      | Example                     |
| ------------- | --------------------------- |
| `runner.os`   | `Linux`, `Windows`, `macOS` |
| `runner.arch` | `X64`, `ARM64`              |


5️⃣ matrix

| Property      | Example                           |
| ------------- | --------------------------------- |
| `matrix.node` | `14`, `16`                        |
| `matrix.os`   | `ubuntu-latest`, `windows-latest` |


6️⃣ steps

| Property                           | Example              |
| ---------------------------------- | -------------------- |
| `steps.build.outputs.artifact_url` | Step output value    |
| `steps.test.conclusion`            | `success`, `failure` |


7️⃣ needs

| Property                      | Example                 |
| ----------------------------- | ----------------------- |
| `needs.build.outputs.version` | Output from job `build` |
| `needs.test.result`           | Status from another job |


8️⃣ inputs

| Property             | Example           |
| -------------------- | ----------------- |
| `inputs.environment` | `"dev"`, `"prod"` |
| `inputs.version`     | `"1.0.3"`         |


9️⃣ vars (Config Variables from GitHub UI - Repository-/organization-/environment-defined variables (via GitHub UI: “Variables” section))

| Property           | Example     |
| ------------------ | ----------- |
| `vars.ENVIRONMENT` | `"staging"` |
| `vars.REGION`      | `"west-us"` |


1️⃣0️⃣ job, jobs

| Property             | Example                |
| -------------------- | ---------------------- |
| `job.status`         | `success`, `failure`   |
| `jobs.deploy.result` | Status of `deploy` job |


-----------------------


| Context Name   | Description                                                                                                                       |
| -------------- | --------------------------------------------------------------------------------------------------------------------------------- |
| **`github`**   | Data about the workflow run, repository, event payload, commit, actor, ref, and more ([docs.github.com][1], [docs.github.com][2]) |
| **`env`**      | Environment variables defined at workflow, job, or step scope                                                                     |
| **`vars`**     | Repository-/organization-/environment-defined variables (via GitHub UI: “Variables” section)                                      |
| **`job`**      | Info about the current job (e.g., `status`)                                                                                       |
| **`jobs`**     | In reusable workflows: outputs and metadata from other jobs                                                                       |
| **`steps`**    | Information and outputs from earlier steps in the same job                                                                        |
| **`runner`**   | Details about the runner executing the job (OS, arch, workspace path)                                                             |
| **`secrets`**  | Secure access to repository or environment secrets                                                                                |
| **`strategy`** | Strategy-level data (e.g., matrix definition, fail-fast, max‑parallel)                                                            |
| **`matrix`**   | Specific values from your matrix strategy for the current job instance                                                            |
| **`needs`**    | Outputs and status from jobs this job depends on                                                                                  |
| **`inputs`**   | Inputs passed via `workflow_dispatch` or reusable workflow arguments                                                              |


-------------------------
⚠️ 4. vars vs env vs secrets
-----------------------

| Feature                    | `vars`                                | `env`                             | `secrets`        |
| -------------------------- | ------------------------------------- | --------------------------------- | ---------------- |
| Purpose                    | Config values shared across workflows | Inline or scoped environment vars | Sensitive info   |
| Defined in                 | GitHub UI/API                         | Workflow YAML or shell script     | GitHub UI        |
| Visibility in logs         | ✅ Visible                             | ✅ Visible                         | ❌ Masked         |
| Scope control              | ✅ (org/repo/env)                      | ✅ (step/job/workflow)             | ✅ (org/repo/env) |
| Can be updated dynamically | ❌                                     | ✅                                 | ❌                |
