name: env vars print in different steps

on: push

env:
  NAME1: "workflow-level"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME1: "job-level"
    steps:
      - name: print env value in first step
        run: |
          echo $NAME1
          echo "--------------------"
          echo "${{ env.NAME1 }}"
        env:
          NAME1: "step-level-1"

      - name: print env value in second step
        run: |
          echo $NAME1
          echo "--------------------"
          echo "${{ env.NAME1 }}"      # It will take value of job env value

      - name: print env value in third step
        run: |
          echo $NAME1
          echo "--------------------"
          echo "${{ env.NAME1 }}"      # It will take value of step-3 value
        env:
          NAME1: "step-level-3"